name: Deploy to Cloudways

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Deploy to Cloudways
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.CLOUDWAYS_SSH_HOST }}
        username: ${{ secrets.CLOUDWAYS_SSH_USER }}
        password: ${{ secrets.CLOUDWAYS_SSH_PASS }}
        port: 22
        script: |
          cd ~/applications/ygrswjnpmw
          
          # If repository doesn't exist, clone it
          if [ ! -d ".git" ]; then
            echo "Repository not found, cloning..."
            rm -rf *
            git clone https://github.com/sosilans/NEWDariasItalianKitchen4.git .
          else
            echo "Repository exists, pulling latest changes..."
            git pull origin main || git pull origin master
          fi
          
          # Make sure we have the deployment script
          if [ -f "ci-bootstrap/deploy.sh" ]; then
            chmod +x ci-bootstrap/deploy.sh
            ./ci-bootstrap/deploy.sh
          else
            echo "Deploy script not found, deploying React build directly..."
            
            # Build React app if needed
            if [ -d "assets/design" ]; then
              cd assets/design
              npm install
              npm run build
              cd ../..
              
              # Copy build files to public_html
              if [ -d "assets/design/build" ]; then
                echo "Copying React build to public_html..."
                
                # Clear public_html first
                rm -rf public_html/*
                
                # Copy all build files
                cp -r assets/design/build/* public_html/
                
                # Set proper permissions
                chmod -R 755 public_html/
                find public_html/ -type f -name "*.html" -exec chmod 644 {} \;
                find public_html/ -type f -name "*.css" -exec chmod 644 {} \;
                find public_html/ -type f -name "*.js" -exec chmod 644 {} \;
                find public_html/ -type f -name "*.png" -exec chmod 644 {} \;
                
                # List files to verify
                echo "Files in public_html:"
                ls -la public_html/
                
                echo "React app deployed successfully!"
              else
                echo "Build failed - no build directory found"
              fi
            else
              echo "No React project found"
            fi
          fi

    - name: Verify deployment
      run: |
        echo "Deployment completed. Checking site status..."
        sleep 30
        curl -f https://phpstack-1511050-5820602.cloudwaysapps.com/ || echo "Site may still be deploying..."
