name: Deploy to Cloudways

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      SSH_HOST: ${{ secrets.CLOUDWAYS_SSH_HOST }}
      SSH_USER: ${{ secrets.CLOUDWAYS_SSH_USER }}
      SSH_PASS: ${{ secrets.CLOUDWAYS_SSH_PASS }}
      SSH_KEY:  ${{ secrets.CLOUDWAYS_SSH_KEY }}
      APP_DIR:  ${{ secrets.CLOUDWAYS_APP_DIR }}
      SERVER_ENV: ${{ secrets.SERVER_ENV }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Prepare known_hosts
        run: |
          mkdir -p ~/.ssh
          if [ -n "$SSH_HOST" ]; then ssh-keyscan -H "$SSH_HOST" >> ~/.ssh/known_hosts; fi

      - name: Deploy (key or password)
        shell: bash
        run: |
          set -e
          if [ -z "$SSH_HOST" ] || [ -z "$SSH_USER" ] || [ -z "$APP_DIR" ]; then
            echo "❌ Missing SSH_HOST/SSH_USER/APP_DIR secrets" >&2; exit 1; fi

          echo "🚀 Starting deployment to $SSH_HOST:$APP_DIR"
          
          if [ -n "$SSH_KEY" ]; then
            echo "🔑 Using SSH key authentication"
            eval "$(ssh-agent -s)"
            ssh-add - <<< "$SSH_KEY"
            
            echo "📤 Syncing files to server..."
            rsync -az --delete -e "ssh -o StrictHostKeyChecking=no" ./ "$SSH_USER@$SSH_HOST:$APP_DIR/"
            
            echo "🚀 Running IMPROVED REACT deployment script on server..."
            ssh -o StrictHostKeyChecking=no "$SSH_USER@$SSH_HOST" "cd $APP_DIR && chmod +x ci-bootstrap/deploy-improved-react.sh && ./ci-bootstrap/deploy-improved-react.sh"
            
          elif [ -n "$SSH_PASS" ]; then
            echo "🔐 Using password authentication"
            sudo apt-get update -y && sudo apt-get install -y sshpass rsync
            
            echo "📤 Syncing files to server..."
            sshpass -p "$SSH_PASS" rsync -az --delete -e "ssh -o StrictHostKeyChecking=no" ./ "$SSH_USER@$SSH_HOST:$APP_DIR/"
            
            echo "🚀 Running IMPROVED REACT deployment script on server..."
            sshpass -p "$SSH_PASS" ssh -o StrictHostKeyChecking=no "$SSH_USER@$SSH_HOST" "cd $APP_DIR && chmod +x ci-bootstrap/deploy-improved-react.sh && ./ci-bootstrap/deploy-improved-react.sh"
            
          else
            echo "❌ No SSH credentials provided" >&2; exit 1; fi
          
          echo "✅ Deployment completed successfully!"

      - name: Health Check
        shell: bash
        run: |
          echo "🏥 Performing health check..."
          if [ -n "$SSH_HOST" ]; then
            if [ -n "$SSH_KEY" ]; then
              eval "$(ssh-agent -s)"
              ssh-add - <<< "$SSH_KEY"
              ssh -o StrictHostKeyChecking=no "$SSH_USER@$SSH_HOST" "curl -f -s https://phpstack-1511050-5820602.cloudwaysapps.com/ || echo 'Health check failed'"
            elif [ -n "$SSH_PASS" ]; then
              sshpass -p "$SSH_PASS" ssh -o StrictHostKeyChecking=no "$SSH_USER@$SSH_HOST" "curl -f -s https://phpstack-1511050-5820602.cloudwaysapps.com/ || echo 'Health check failed'"
            fi
          fi


