name: Deploy to Cloudways

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Deploy to Cloudways
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.CLOUDWAYS_SSH_HOST }}
        username: ${{ secrets.CLOUDWAYS_SSH_USER }}
        password: ${{ secrets.CLOUDWAYS_SSH_PASS }}
        port: 22
        script: |
          echo "=== DEPLOYMENT DEBUG INFO ==="
          echo "Current user: $(whoami)"
          echo "Current directory: $(pwd)"
          echo "Home directory: $HOME"
          echo "Available space: $(df -h . | tail -1)"
          
          cd ~/applications/ygrswjnpmw
          echo "App directory: $(pwd)"
          echo "Directory contents before:"
          ls -la
          
          # If repository doesn't exist, clone it
          if [ ! -d ".git" ]; then
            echo "Repository not found, cloning..."
            # Create a separate directory for our code
            mkdir -p website_code
            cd website_code
            git clone https://github.com/sosilans/NEWDariasItalianKitchen4.git .
            cd ..
          else
            echo "Repository exists, pulling latest changes..."
            cd website_code
            git pull origin main || git pull origin master
            cd ..
          fi
          
          echo "Directory contents after git:"
          ls -la
          
          # Check for NEW_FRONTEND directory
          if [ -d "website_code/NEW_FRONTEND" ]; then
            echo "Found NEW_FRONTEND directory, deploying..."
            
            # Clear public_html first
            rm -rf public_html/*
            
            # Copy all files from NEW_FRONTEND (except README and scripts)
            find website_code/NEW_FRONTEND -type f ! -name "README.md" ! -name "*.ps1" -exec cp {} public_html/ \;
            
            # Copy directories
            for dir in website_code/NEW_FRONTEND/*/; do
              if [ -d "$dir" ]; then
                dirname=$(basename "$dir")
                cp -r "$dir" public_html/
              fi
            done
            
            # Set proper permissions for web access
            chmod -R 755 public_html/
            find public_html/ -type f -exec chmod 644 {} \;
            
            echo "=== NEW FRONTEND DEPLOYED ==="
            ls -la public_html/
            
          else
            echo "No NEW_FRONTEND directory found, keeping placeholder..."
            echo "To deploy new frontend:"
            echo "1. Add files to NEW_FRONTEND/ directory"
            echo "2. Push to GitHub"
            echo "3. Deployment will happen automatically"
          fi

    - name: Verify deployment
      run: |
        echo "Deployment completed. Checking site status..."
        sleep 30
        curl -f https://phpstack-1511050-5820602.cloudwaysapps.com/ || echo "Site may still be deploying..."
